---
title: "Research"
---

Zhu, Z. 2025. "[Reconfiguring Hierarchies: Japan's Pursuit of Networked Security Framework in a Contested Indo-Pacific.](https://www.saisjournal.eu//article/112-Reconfiguring-Hierarchies-Japans-Pursuit-of-Networked-Security-in-a-Contested-In.cfm)" *SAIS Europe Journal of Global Affairs* 28(1): 78-96.

-   *Summary*: This paper examines Japan’s evolving security strategy under Prime Minister Abe’s second premiership, situating it within broader structural transformations in East Asia’s regional order. Anchored in the hedging school of neorealist thought, the analysis traces how Japan’s strategic posture has shifted in response to perceived limitations within the U.S.-led “hub-and-spoke” alliance system. Conceptualizing this moment as a critical juncture, the paper argues that Japan’s recalibration toward a networked security framework—manifested through the Free and Open Indo-Pacific (FOIP) vision and the revitalization of the Quadrilateral Security Dialogue (Quad)—constitutes a deliberate effort to complement bilateral alliances with inter-spoke and minilateral cooperation.
